site_name: Docker Study Notes
site_url: http://docker-study.shams-nahid.com/
site_description: Docker Study notes during CSAA certifications
site_author: Shams Nahid

repo_url: https://github.com/bmshamsnahid/My-Docker-Study
edit_uri: ''

extra_css:
  - css/extra.css

copyright: Copyright &copy; 2021 <a href="https://shams-nahid.com/">Shams Nahid</a>.
