language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t docker_user_name/ix-docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true docker_user_name/ix-docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "ap-south-1"
  app: "ix-docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-ap-south-1-366735605679"
  bucket_path: "ix-docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY